/* Generated by Yosys 0.64 (git sha1 6d2c445ae, g++ 11.4.0-1ubuntu1~22.04.3 -fPIC -O3) */

(* dynports =  1  *)
(* top =  1  *)
(* src = "asy_FIFO.v:4.1-32.10" *)
module asy_FIFO(data_in, w_en, r_en, wclk, rclk, bin_w_ptr, bin_r_ptr, full, empty, data_out, reset);
  (* src = "asy_FIFO.v:5.21-5.28" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "asy_FIFO.v:6.7-6.11" *)
  input w_en;
  wire w_en;
  (* src = "asy_FIFO.v:6.12-6.16" *)
  input r_en;
  wire r_en;
  (* src = "asy_FIFO.v:7.7-7.11" *)
  input wclk;
  wire wclk;
  (* src = "asy_FIFO.v:7.12-7.16" *)
  input rclk;
  wire rclk;
  (* src = "asy_FIFO.v:8.31-8.40" *)
  output [3:0] bin_w_ptr;
  wire [3:0] bin_w_ptr;
  (* src = "asy_FIFO.v:8.41-8.50" *)
  output [3:0] bin_r_ptr;
  wire [3:0] bin_r_ptr;
  (* src = "asy_FIFO.v:9.8-9.12" *)
  output full;
  wire full;
  (* src = "asy_FIFO.v:9.13-9.18" *)
  output empty;
  wire empty;
  (* src = "asy_FIFO.v:10.27-10.35" *)
  output [31:0] data_out;
  wire [31:0] data_out;
  (* src = "asy_FIFO.v:11.7-11.12" *)
  input reset;
  wire reset;
  (* module_not_derived = 32'd1 *)
  (* src = "asy_FIFO.v:13.16-21.34" *)
  top_module uut (
    .bin_r_ptr(bin_r_ptr),
    .bin_w_ptr(bin_w_ptr),
    .empty(empty),
    .full(full),
    .r_en(r_en),
    .rclk(rclk),
    .reset(reset),
    .w_en(w_en),
    .wclk(wclk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "asy_FIFO.v:22.17-31.43" *)
  pseudo_dual uut1 (
    .bin_r_ptr(bin_r_ptr),
    .bin_w_ptr(bin_w_ptr),
    .data_in(data_in),
    .data_out(data_out),
    .empty(empty),
    .full(full),
    .r_en(r_en),
    .rclk(rclk),
    .w_en(w_en),
    .wclk(wclk)
  );
endmodule

(* dynports =  1  *)
(* src = "bcd_gray.v:4.1-16.10" *)
module bcd_gray(bin_addr, gray_addr);
  (* src = "bcd_gray.v:5.25-5.33" *)
  input [3:0] bin_addr;
  wire [3:0] bin_addr;
  (* src = "bcd_gray.v:6.30-6.39" *)
  output [3:0] gray_addr;
  wire [3:0] gray_addr;
  (* src = "bcd_gray.v:8.13-8.14" *)
  wire [31:0] i;
  sky130_fd_sc_hd__xor2_1 _0_ (
    .A(bin_addr[1]),
    .B(bin_addr[0]),
    .X(gray_addr[0])
  );
  sky130_fd_sc_hd__xor2_1 _1_ (
    .A(bin_addr[1]),
    .B(bin_addr[2]),
    .X(gray_addr[1])
  );
  sky130_fd_sc_hd__xor2_1 _2_ (
    .A(bin_addr[2]),
    .B(bin_addr[3]),
    .X(gray_addr[2])
  );
  assign i = 32'd4294967295;
  assign gray_addr[3] = bin_addr[3];
endmodule

(* dynports =  1  *)
(* src = "d_ff.v:5.1-13.10" *)
module d_ff(clk, d, q);
  (* src = "d_ff.v:6.7-6.10" *)
  input clk;
  wire clk;
  (* src = "d_ff.v:7.24-7.25" *)
  input [3:0] d;
  wire [3:0] d;
  (* src = "d_ff.v:8.29-8.30" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "d_ff.v:10.5-12.8" *)
  sky130_fd_sc_hd__dfxtp_1 _0_ (
    .CLK(clk),
    .D(d[0]),
    .Q(q[0])
  );
  (* src = "d_ff.v:10.5-12.8" *)
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(d[1]),
    .Q(q[1])
  );
  (* src = "d_ff.v:10.5-12.8" *)
  sky130_fd_sc_hd__dfxtp_1 _2_ (
    .CLK(clk),
    .D(d[2]),
    .Q(q[2])
  );
  (* src = "d_ff.v:10.5-12.8" *)
  sky130_fd_sc_hd__dfxtp_1 _3_ (
    .CLK(clk),
    .D(d[3]),
    .Q(q[3])
  );
endmodule

(* dynports =  1  *)
(* src = "gray_bcd.v:4.1-16.10" *)
module gray_bcd(gray_addr, bin_addr);
  (* src = "gray_bcd.v:5.25-5.34" *)
  input [3:0] gray_addr;
  wire [3:0] gray_addr;
  (* src = "gray_bcd.v:6.30-6.38" *)
  output [3:0] bin_addr;
  wire [3:0] bin_addr;
  wire _0_;
  (* src = "gray_bcd.v:8.13-8.14" *)
  wire [31:0] i;
  sky130_fd_sc_hd__xnor2_1 _1_ (
    .A(gray_addr[3]),
    .B(gray_addr[2]),
    .Y(_0_)
  );
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(_0_),
    .Y(bin_addr[2])
  );
  sky130_fd_sc_hd__xnor2_1 _3_ (
    .A(gray_addr[1]),
    .B(_0_),
    .Y(bin_addr[1])
  );
  sky130_fd_sc_hd__xnor3_1 _4_ (
    .A(gray_addr[1]),
    .B(gray_addr[0]),
    .C(_0_),
    .X(bin_addr[0])
  );
  assign i = 32'd4294967295;
  assign bin_addr[3] = gray_addr[3];
endmodule

(* dynports =  1  *)
(* src = "pseudo_dual.v:4.1-24.10" *)
module pseudo_dual(bin_w_ptr, bin_r_ptr, full, empty, wclk, rclk, w_en, r_en, data_in, data_out);
  (* src = "pseudo_dual.v:5.25-5.34" *)
  input [3:0] bin_w_ptr;
  wire [3:0] bin_w_ptr;
  (* src = "pseudo_dual.v:6.25-6.34" *)
  input [3:0] bin_r_ptr;
  wire [3:0] bin_r_ptr;
  (* src = "pseudo_dual.v:7.7-7.11" *)
  input full;
  wire full;
  (* src = "pseudo_dual.v:7.12-7.17" *)
  input empty;
  wire empty;
  (* src = "pseudo_dual.v:8.7-8.11" *)
  input wclk;
  wire wclk;
  (* src = "pseudo_dual.v:8.12-8.16" *)
  input rclk;
  wire rclk;
  (* src = "pseudo_dual.v:9.7-9.11" *)
  input w_en;
  wire w_en;
  (* src = "pseudo_dual.v:9.12-9.16" *)
  input r_en;
  wire r_en;
  (* src = "pseudo_dual.v:10.21-10.28" *)
  input [31:0] data_in;
  wire [31:0] data_in;
  (* src = "pseudo_dual.v:11.26-11.34" *)
  output [31:0] data_out;
  wire [31:0] data_out;
  wire [31:0] _000_;
  (* src = "pseudo_dual.v:21.8-21.22" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire [31:0] \mem[0] ;
  wire [31:0] \mem[1] ;
  wire [31:0] \mem[2] ;
  wire [31:0] \mem[3] ;
  wire [31:0] \mem[4] ;
  wire [31:0] \mem[5] ;
  wire [31:0] \mem[6] ;
  wire [31:0] \mem[7] ;
  sky130_fd_sc_hd__mux4_2 _079_ (
    .A0(\mem[1] [30]),
    .A1(\mem[5] [30]),
    .A2(\mem[3] [30]),
    .A3(\mem[7] [30]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux4_2 _080_ (
    .A0(\mem[0] [30]),
    .A1(\mem[4] [30]),
    .A2(\mem[2] [30]),
    .A3(\mem[6] [30]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _081_ (
    .A0(_011_),
    .A1(_010_),
    .S(bin_r_ptr[0]),
    .X(_000_[30])
  );
  sky130_fd_sc_hd__mux4_2 _082_ (
    .A0(\mem[1] [29]),
    .A1(\mem[5] [29]),
    .A2(\mem[3] [29]),
    .A3(\mem[7] [29]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux4_2 _083_ (
    .A0(\mem[0] [29]),
    .A1(\mem[4] [29]),
    .A2(\mem[2] [29]),
    .A3(\mem[6] [29]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _084_ (
    .A0(_013_),
    .A1(_012_),
    .S(bin_r_ptr[0]),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__mux4_2 _085_ (
    .A0(\mem[1] [28]),
    .A1(\mem[5] [28]),
    .A2(\mem[3] [28]),
    .A3(\mem[7] [28]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux4_2 _086_ (
    .A0(\mem[0] [28]),
    .A1(\mem[4] [28]),
    .A2(\mem[2] [28]),
    .A3(\mem[6] [28]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _087_ (
    .A0(_015_),
    .A1(_014_),
    .S(bin_r_ptr[0]),
    .X(_000_[28])
  );
  sky130_fd_sc_hd__mux4_2 _088_ (
    .A0(\mem[1] [27]),
    .A1(\mem[5] [27]),
    .A2(\mem[3] [27]),
    .A3(\mem[7] [27]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux4_2 _089_ (
    .A0(\mem[0] [27]),
    .A1(\mem[4] [27]),
    .A2(\mem[2] [27]),
    .A3(\mem[6] [27]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _090_ (
    .A0(_017_),
    .A1(_016_),
    .S(bin_r_ptr[0]),
    .X(_000_[27])
  );
  sky130_fd_sc_hd__mux4_2 _091_ (
    .A0(\mem[1] [26]),
    .A1(\mem[5] [26]),
    .A2(\mem[3] [26]),
    .A3(\mem[7] [26]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux4_2 _092_ (
    .A0(\mem[0] [26]),
    .A1(\mem[4] [26]),
    .A2(\mem[2] [26]),
    .A3(\mem[6] [26]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _093_ (
    .A0(_019_),
    .A1(_018_),
    .S(bin_r_ptr[0]),
    .X(_000_[26])
  );
  sky130_fd_sc_hd__mux4_2 _094_ (
    .A0(\mem[1] [25]),
    .A1(\mem[5] [25]),
    .A2(\mem[3] [25]),
    .A3(\mem[7] [25]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux4_2 _095_ (
    .A0(\mem[0] [25]),
    .A1(\mem[4] [25]),
    .A2(\mem[2] [25]),
    .A3(\mem[6] [25]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _096_ (
    .A0(_021_),
    .A1(_020_),
    .S(bin_r_ptr[0]),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__mux4_2 _097_ (
    .A0(\mem[1] [24]),
    .A1(\mem[5] [24]),
    .A2(\mem[3] [24]),
    .A3(\mem[7] [24]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux4_2 _098_ (
    .A0(\mem[0] [24]),
    .A1(\mem[4] [24]),
    .A2(\mem[2] [24]),
    .A3(\mem[6] [24]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(_023_),
    .A1(_022_),
    .S(bin_r_ptr[0]),
    .X(_000_[24])
  );
  sky130_fd_sc_hd__mux4_2 _100_ (
    .A0(\mem[1] [23]),
    .A1(\mem[5] [23]),
    .A2(\mem[3] [23]),
    .A3(\mem[7] [23]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux4_2 _101_ (
    .A0(\mem[0] [23]),
    .A1(\mem[4] [23]),
    .A2(\mem[2] [23]),
    .A3(\mem[6] [23]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(_025_),
    .A1(_024_),
    .S(bin_r_ptr[0]),
    .X(_000_[23])
  );
  sky130_fd_sc_hd__mux4_2 _103_ (
    .A0(\mem[1] [22]),
    .A1(\mem[5] [22]),
    .A2(\mem[3] [22]),
    .A3(\mem[7] [22]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux4_2 _104_ (
    .A0(\mem[0] [22]),
    .A1(\mem[4] [22]),
    .A2(\mem[2] [22]),
    .A3(\mem[6] [22]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(_027_),
    .A1(_026_),
    .S(bin_r_ptr[0]),
    .X(_000_[22])
  );
  sky130_fd_sc_hd__mux4_2 _106_ (
    .A0(\mem[1] [21]),
    .A1(\mem[5] [21]),
    .A2(\mem[3] [21]),
    .A3(\mem[7] [21]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux4_2 _107_ (
    .A0(\mem[0] [21]),
    .A1(\mem[4] [21]),
    .A2(\mem[2] [21]),
    .A3(\mem[6] [21]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(_029_),
    .A1(_028_),
    .S(bin_r_ptr[0]),
    .X(_000_[21])
  );
  sky130_fd_sc_hd__mux4_2 _109_ (
    .A0(\mem[1] [20]),
    .A1(\mem[5] [20]),
    .A2(\mem[3] [20]),
    .A3(\mem[7] [20]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux4_2 _110_ (
    .A0(\mem[0] [20]),
    .A1(\mem[4] [20]),
    .A2(\mem[2] [20]),
    .A3(\mem[6] [20]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(_031_),
    .A1(_030_),
    .S(bin_r_ptr[0]),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__mux4_2 _112_ (
    .A0(\mem[1] [19]),
    .A1(\mem[5] [19]),
    .A2(\mem[3] [19]),
    .A3(\mem[7] [19]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux4_2 _113_ (
    .A0(\mem[0] [19]),
    .A1(\mem[4] [19]),
    .A2(\mem[2] [19]),
    .A3(\mem[6] [19]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(_033_),
    .A1(_032_),
    .S(bin_r_ptr[0]),
    .X(_000_[19])
  );
  sky130_fd_sc_hd__mux4_2 _115_ (
    .A0(\mem[1] [18]),
    .A1(\mem[5] [18]),
    .A2(\mem[3] [18]),
    .A3(\mem[7] [18]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux4_2 _116_ (
    .A0(\mem[0] [18]),
    .A1(\mem[4] [18]),
    .A2(\mem[2] [18]),
    .A3(\mem[6] [18]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _117_ (
    .A0(_035_),
    .A1(_034_),
    .S(bin_r_ptr[0]),
    .X(_000_[18])
  );
  sky130_fd_sc_hd__mux4_2 _118_ (
    .A0(\mem[1] [17]),
    .A1(\mem[5] [17]),
    .A2(\mem[3] [17]),
    .A3(\mem[7] [17]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux4_2 _119_ (
    .A0(\mem[0] [17]),
    .A1(\mem[4] [17]),
    .A2(\mem[2] [17]),
    .A3(\mem[6] [17]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _120_ (
    .A0(_037_),
    .A1(_036_),
    .S(bin_r_ptr[0]),
    .X(_000_[17])
  );
  sky130_fd_sc_hd__mux4_2 _121_ (
    .A0(\mem[1] [16]),
    .A1(\mem[5] [16]),
    .A2(\mem[3] [16]),
    .A3(\mem[7] [16]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_038_)
  );
  sky130_fd_sc_hd__mux4_2 _122_ (
    .A0(\mem[0] [16]),
    .A1(\mem[4] [16]),
    .A2(\mem[2] [16]),
    .A3(\mem[6] [16]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _123_ (
    .A0(_039_),
    .A1(_038_),
    .S(bin_r_ptr[0]),
    .X(_000_[16])
  );
  sky130_fd_sc_hd__mux4_2 _124_ (
    .A0(\mem[1] [15]),
    .A1(\mem[5] [15]),
    .A2(\mem[3] [15]),
    .A3(\mem[7] [15]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux4_2 _125_ (
    .A0(\mem[0] [15]),
    .A1(\mem[4] [15]),
    .A2(\mem[2] [15]),
    .A3(\mem[6] [15]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _126_ (
    .A0(_041_),
    .A1(_040_),
    .S(bin_r_ptr[0]),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__mux4_2 _127_ (
    .A0(\mem[1] [14]),
    .A1(\mem[5] [14]),
    .A2(\mem[3] [14]),
    .A3(\mem[7] [14]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux4_2 _128_ (
    .A0(\mem[0] [14]),
    .A1(\mem[4] [14]),
    .A2(\mem[2] [14]),
    .A3(\mem[6] [14]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _129_ (
    .A0(_043_),
    .A1(_042_),
    .S(bin_r_ptr[0]),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__mux4_2 _130_ (
    .A0(\mem[1] [13]),
    .A1(\mem[5] [13]),
    .A2(\mem[3] [13]),
    .A3(\mem[7] [13]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux4_2 _131_ (
    .A0(\mem[0] [13]),
    .A1(\mem[4] [13]),
    .A2(\mem[2] [13]),
    .A3(\mem[6] [13]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_045_)
  );
  sky130_fd_sc_hd__mux2_1 _132_ (
    .A0(_045_),
    .A1(_044_),
    .S(bin_r_ptr[0]),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__mux4_2 _133_ (
    .A0(\mem[1] [12]),
    .A1(\mem[5] [12]),
    .A2(\mem[3] [12]),
    .A3(\mem[7] [12]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_046_)
  );
  sky130_fd_sc_hd__mux4_2 _134_ (
    .A0(\mem[0] [12]),
    .A1(\mem[4] [12]),
    .A2(\mem[2] [12]),
    .A3(\mem[6] [12]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_047_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(_047_),
    .A1(_046_),
    .S(bin_r_ptr[0]),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__mux4_2 _136_ (
    .A0(\mem[1] [11]),
    .A1(\mem[5] [11]),
    .A2(\mem[3] [11]),
    .A3(\mem[7] [11]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_048_)
  );
  sky130_fd_sc_hd__mux4_2 _137_ (
    .A0(\mem[0] [11]),
    .A1(\mem[4] [11]),
    .A2(\mem[2] [11]),
    .A3(\mem[6] [11]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_049_)
  );
  sky130_fd_sc_hd__mux2_1 _138_ (
    .A0(_049_),
    .A1(_048_),
    .S(bin_r_ptr[0]),
    .X(_000_[11])
  );
  sky130_fd_sc_hd__mux4_2 _139_ (
    .A0(\mem[1] [10]),
    .A1(\mem[5] [10]),
    .A2(\mem[3] [10]),
    .A3(\mem[7] [10]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_050_)
  );
  sky130_fd_sc_hd__mux4_2 _140_ (
    .A0(\mem[0] [10]),
    .A1(\mem[4] [10]),
    .A2(\mem[2] [10]),
    .A3(\mem[6] [10]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_051_)
  );
  sky130_fd_sc_hd__mux2_1 _141_ (
    .A0(_051_),
    .A1(_050_),
    .S(bin_r_ptr[0]),
    .X(_000_[10])
  );
  sky130_fd_sc_hd__mux4_2 _142_ (
    .A0(\mem[1] [9]),
    .A1(\mem[5] [9]),
    .A2(\mem[3] [9]),
    .A3(\mem[7] [9]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_052_)
  );
  sky130_fd_sc_hd__mux4_2 _143_ (
    .A0(\mem[0] [9]),
    .A1(\mem[4] [9]),
    .A2(\mem[2] [9]),
    .A3(\mem[6] [9]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_053_)
  );
  sky130_fd_sc_hd__mux2_1 _144_ (
    .A0(_053_),
    .A1(_052_),
    .S(bin_r_ptr[0]),
    .X(_000_[9])
  );
  sky130_fd_sc_hd__mux4_2 _145_ (
    .A0(\mem[1] [8]),
    .A1(\mem[5] [8]),
    .A2(\mem[3] [8]),
    .A3(\mem[7] [8]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_054_)
  );
  sky130_fd_sc_hd__mux4_2 _146_ (
    .A0(\mem[0] [8]),
    .A1(\mem[4] [8]),
    .A2(\mem[2] [8]),
    .A3(\mem[6] [8]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_055_)
  );
  sky130_fd_sc_hd__mux2_1 _147_ (
    .A0(_055_),
    .A1(_054_),
    .S(bin_r_ptr[0]),
    .X(_000_[8])
  );
  sky130_fd_sc_hd__mux4_2 _148_ (
    .A0(\mem[1] [7]),
    .A1(\mem[5] [7]),
    .A2(\mem[3] [7]),
    .A3(\mem[7] [7]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_056_)
  );
  sky130_fd_sc_hd__mux4_2 _149_ (
    .A0(\mem[0] [7]),
    .A1(\mem[4] [7]),
    .A2(\mem[2] [7]),
    .A3(\mem[6] [7]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_057_)
  );
  sky130_fd_sc_hd__mux2_1 _150_ (
    .A0(_057_),
    .A1(_056_),
    .S(bin_r_ptr[0]),
    .X(_000_[7])
  );
  sky130_fd_sc_hd__mux4_2 _151_ (
    .A0(\mem[1] [6]),
    .A1(\mem[5] [6]),
    .A2(\mem[3] [6]),
    .A3(\mem[7] [6]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_058_)
  );
  sky130_fd_sc_hd__mux4_2 _152_ (
    .A0(\mem[0] [6]),
    .A1(\mem[4] [6]),
    .A2(\mem[2] [6]),
    .A3(\mem[6] [6]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_059_)
  );
  sky130_fd_sc_hd__mux2_1 _153_ (
    .A0(_059_),
    .A1(_058_),
    .S(bin_r_ptr[0]),
    .X(_000_[6])
  );
  sky130_fd_sc_hd__mux4_2 _154_ (
    .A0(\mem[1] [5]),
    .A1(\mem[5] [5]),
    .A2(\mem[3] [5]),
    .A3(\mem[7] [5]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_060_)
  );
  sky130_fd_sc_hd__mux4_2 _155_ (
    .A0(\mem[0] [5]),
    .A1(\mem[4] [5]),
    .A2(\mem[2] [5]),
    .A3(\mem[6] [5]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_061_)
  );
  sky130_fd_sc_hd__mux2_1 _156_ (
    .A0(_061_),
    .A1(_060_),
    .S(bin_r_ptr[0]),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__mux4_2 _157_ (
    .A0(\mem[1] [4]),
    .A1(\mem[5] [4]),
    .A2(\mem[3] [4]),
    .A3(\mem[7] [4]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_062_)
  );
  sky130_fd_sc_hd__mux4_2 _158_ (
    .A0(\mem[0] [4]),
    .A1(\mem[4] [4]),
    .A2(\mem[2] [4]),
    .A3(\mem[6] [4]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_063_)
  );
  sky130_fd_sc_hd__mux2_1 _159_ (
    .A0(_063_),
    .A1(_062_),
    .S(bin_r_ptr[0]),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__mux4_2 _160_ (
    .A0(\mem[1] [3]),
    .A1(\mem[5] [3]),
    .A2(\mem[3] [3]),
    .A3(\mem[7] [3]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_064_)
  );
  sky130_fd_sc_hd__mux4_2 _161_ (
    .A0(\mem[0] [3]),
    .A1(\mem[4] [3]),
    .A2(\mem[2] [3]),
    .A3(\mem[6] [3]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_065_)
  );
  sky130_fd_sc_hd__mux2_1 _162_ (
    .A0(_065_),
    .A1(_064_),
    .S(bin_r_ptr[0]),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__mux4_2 _163_ (
    .A0(\mem[1] [2]),
    .A1(\mem[5] [2]),
    .A2(\mem[3] [2]),
    .A3(\mem[7] [2]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_066_)
  );
  sky130_fd_sc_hd__mux4_2 _164_ (
    .A0(\mem[0] [2]),
    .A1(\mem[4] [2]),
    .A2(\mem[2] [2]),
    .A3(\mem[6] [2]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_067_)
  );
  sky130_fd_sc_hd__mux2_1 _165_ (
    .A0(_067_),
    .A1(_066_),
    .S(bin_r_ptr[0]),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__mux4_2 _166_ (
    .A0(\mem[1] [1]),
    .A1(\mem[5] [1]),
    .A2(\mem[3] [1]),
    .A3(\mem[7] [1]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_068_)
  );
  sky130_fd_sc_hd__mux4_2 _167_ (
    .A0(\mem[0] [1]),
    .A1(\mem[4] [1]),
    .A2(\mem[2] [1]),
    .A3(\mem[6] [1]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_069_)
  );
  sky130_fd_sc_hd__mux2_1 _168_ (
    .A0(_069_),
    .A1(_068_),
    .S(bin_r_ptr[0]),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__mux4_2 _169_ (
    .A0(\mem[1] [0]),
    .A1(\mem[5] [0]),
    .A2(\mem[3] [0]),
    .A3(\mem[7] [0]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_070_)
  );
  sky130_fd_sc_hd__mux4_2 _170_ (
    .A0(\mem[0] [0]),
    .A1(\mem[4] [0]),
    .A2(\mem[2] [0]),
    .A3(\mem[6] [0]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_071_)
  );
  sky130_fd_sc_hd__mux2_1 _171_ (
    .A0(_071_),
    .A1(_070_),
    .S(bin_r_ptr[0]),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__nand2_1 _172_ (
    .A(bin_w_ptr[2]),
    .B(bin_w_ptr[1]),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand3b_1 _173_ (
    .A_N(full),
    .B(bin_w_ptr[0]),
    .C(w_en),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _174_ (
    .A(_072_),
    .B(_073_),
    .Y(_009_)
  );
  sky130_fd_sc_hd__nand2b_1 _175_ (
    .A_N(bin_w_ptr[2]),
    .B(bin_w_ptr[1]),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _176_ (
    .A(_073_),
    .B(_074_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__or3b_1 _177_ (
    .A(full),
    .B(bin_w_ptr[0]),
    .C_N(w_en),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _178_ (
    .A(_072_),
    .B(_075_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__nor2_1 _179_ (
    .A(_074_),
    .B(_075_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__nand2b_1 _180_ (
    .A_N(bin_w_ptr[1]),
    .B(bin_w_ptr[2]),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _181_ (
    .A(_073_),
    .B(_076_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nor3_1 _182_ (
    .A(bin_w_ptr[2]),
    .B(bin_w_ptr[1]),
    .C(_073_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nor3_1 _183_ (
    .A(bin_w_ptr[2]),
    .B(bin_w_ptr[1]),
    .C(_075_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__mux4_2 _184_ (
    .A0(\mem[1] [31]),
    .A1(\mem[5] [31]),
    .A2(\mem[3] [31]),
    .A3(\mem[7] [31]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_077_)
  );
  sky130_fd_sc_hd__mux4_2 _185_ (
    .A0(\mem[0] [31]),
    .A1(\mem[4] [31]),
    .A2(\mem[2] [31]),
    .A3(\mem[6] [31]),
    .S0(bin_r_ptr[2]),
    .S1(bin_r_ptr[1]),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _186_ (
    .A0(_078_),
    .A1(_077_),
    .S(bin_r_ptr[0]),
    .X(_000_[31])
  );
  sky130_fd_sc_hd__nor2_1 _187_ (
    .A(_075_),
    .B(_076_),
    .Y(_006_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _188_ (
    .A(r_en),
    .SLEEP(empty),
    .X(_001_)
  );
  sky130_fd_sc_hd__edfxtp_1 _189_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_009_),
    .Q(\mem[7] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _190_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_009_),
    .Q(\mem[7] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _191_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_009_),
    .Q(\mem[7] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _192_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_009_),
    .Q(\mem[7] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _193_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_009_),
    .Q(\mem[7] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _194_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_009_),
    .Q(\mem[7] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _195_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_009_),
    .Q(\mem[7] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _196_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_009_),
    .Q(\mem[7] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _197_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_009_),
    .Q(\mem[7] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _198_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_009_),
    .Q(\mem[7] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _199_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_009_),
    .Q(\mem[7] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _200_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_009_),
    .Q(\mem[7] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _201_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_009_),
    .Q(\mem[7] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _202_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_009_),
    .Q(\mem[7] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _203_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_009_),
    .Q(\mem[7] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _204_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_009_),
    .Q(\mem[7] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _205_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_009_),
    .Q(\mem[7] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _206_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_009_),
    .Q(\mem[7] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _207_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_009_),
    .Q(\mem[7] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _208_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_009_),
    .Q(\mem[7] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _209_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_009_),
    .Q(\mem[7] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _210_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_009_),
    .Q(\mem[7] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _211_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_009_),
    .Q(\mem[7] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _212_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_009_),
    .Q(\mem[7] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _213_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_009_),
    .Q(\mem[7] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _214_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_009_),
    .Q(\mem[7] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _215_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_009_),
    .Q(\mem[7] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _216_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_009_),
    .Q(\mem[7] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _217_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_009_),
    .Q(\mem[7] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _218_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_009_),
    .Q(\mem[7] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _219_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_009_),
    .Q(\mem[7] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _220_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_009_),
    .Q(\mem[7] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _221_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_008_),
    .Q(\mem[6] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _222_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_008_),
    .Q(\mem[6] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _223_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_008_),
    .Q(\mem[6] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _224_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_008_),
    .Q(\mem[6] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _225_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_008_),
    .Q(\mem[6] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _226_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_008_),
    .Q(\mem[6] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _227_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_008_),
    .Q(\mem[6] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _228_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_008_),
    .Q(\mem[6] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _229_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_008_),
    .Q(\mem[6] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _230_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_008_),
    .Q(\mem[6] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _231_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_008_),
    .Q(\mem[6] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _232_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_008_),
    .Q(\mem[6] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _233_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_008_),
    .Q(\mem[6] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _234_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_008_),
    .Q(\mem[6] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _235_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_008_),
    .Q(\mem[6] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _236_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_008_),
    .Q(\mem[6] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _237_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_008_),
    .Q(\mem[6] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _238_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_008_),
    .Q(\mem[6] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _239_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_008_),
    .Q(\mem[6] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _240_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_008_),
    .Q(\mem[6] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _241_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_008_),
    .Q(\mem[6] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _242_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_008_),
    .Q(\mem[6] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _243_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_008_),
    .Q(\mem[6] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _244_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_008_),
    .Q(\mem[6] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _245_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_008_),
    .Q(\mem[6] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _246_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_008_),
    .Q(\mem[6] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _247_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_008_),
    .Q(\mem[6] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _248_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_008_),
    .Q(\mem[6] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _249_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_008_),
    .Q(\mem[6] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _250_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_008_),
    .Q(\mem[6] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _251_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_008_),
    .Q(\mem[6] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _252_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_008_),
    .Q(\mem[6] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _253_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_007_),
    .Q(\mem[5] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _254_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_007_),
    .Q(\mem[5] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _255_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_007_),
    .Q(\mem[5] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _256_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_007_),
    .Q(\mem[5] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _257_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_007_),
    .Q(\mem[5] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _258_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_007_),
    .Q(\mem[5] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _259_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_007_),
    .Q(\mem[5] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _260_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_007_),
    .Q(\mem[5] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _261_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_007_),
    .Q(\mem[5] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _262_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_007_),
    .Q(\mem[5] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _263_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_007_),
    .Q(\mem[5] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _264_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_007_),
    .Q(\mem[5] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _265_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_007_),
    .Q(\mem[5] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _266_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_007_),
    .Q(\mem[5] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _267_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_007_),
    .Q(\mem[5] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _268_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_007_),
    .Q(\mem[5] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _269_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_007_),
    .Q(\mem[5] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _270_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_007_),
    .Q(\mem[5] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _271_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_007_),
    .Q(\mem[5] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _272_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_007_),
    .Q(\mem[5] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _273_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_007_),
    .Q(\mem[5] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _274_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_007_),
    .Q(\mem[5] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _275_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_007_),
    .Q(\mem[5] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _276_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_007_),
    .Q(\mem[5] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _277_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_007_),
    .Q(\mem[5] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _278_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_007_),
    .Q(\mem[5] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _279_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_007_),
    .Q(\mem[5] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _280_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_007_),
    .Q(\mem[5] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _281_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_007_),
    .Q(\mem[5] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _282_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_007_),
    .Q(\mem[5] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _283_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_007_),
    .Q(\mem[5] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _284_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_007_),
    .Q(\mem[5] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _285_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_006_),
    .Q(\mem[4] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _286_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_006_),
    .Q(\mem[4] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _287_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_006_),
    .Q(\mem[4] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _288_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_006_),
    .Q(\mem[4] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _289_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_006_),
    .Q(\mem[4] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _290_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_006_),
    .Q(\mem[4] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _291_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_006_),
    .Q(\mem[4] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _292_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_006_),
    .Q(\mem[4] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _293_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_006_),
    .Q(\mem[4] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _294_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_006_),
    .Q(\mem[4] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _295_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_006_),
    .Q(\mem[4] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _296_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_006_),
    .Q(\mem[4] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _297_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_006_),
    .Q(\mem[4] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _298_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_006_),
    .Q(\mem[4] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _299_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_006_),
    .Q(\mem[4] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _300_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_006_),
    .Q(\mem[4] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _301_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_006_),
    .Q(\mem[4] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _302_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_006_),
    .Q(\mem[4] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _303_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_006_),
    .Q(\mem[4] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _304_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_006_),
    .Q(\mem[4] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _305_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_006_),
    .Q(\mem[4] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _306_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_006_),
    .Q(\mem[4] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _307_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_006_),
    .Q(\mem[4] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _308_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_006_),
    .Q(\mem[4] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _309_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_006_),
    .Q(\mem[4] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _310_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_006_),
    .Q(\mem[4] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _311_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_006_),
    .Q(\mem[4] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _312_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_006_),
    .Q(\mem[4] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _313_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_006_),
    .Q(\mem[4] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _314_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_006_),
    .Q(\mem[4] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _315_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_006_),
    .Q(\mem[4] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _316_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_006_),
    .Q(\mem[4] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _317_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_005_),
    .Q(\mem[3] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _318_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_005_),
    .Q(\mem[3] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _319_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_005_),
    .Q(\mem[3] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _320_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_005_),
    .Q(\mem[3] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _321_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_005_),
    .Q(\mem[3] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _322_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_005_),
    .Q(\mem[3] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _323_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_005_),
    .Q(\mem[3] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _324_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_005_),
    .Q(\mem[3] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _325_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_005_),
    .Q(\mem[3] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _326_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_005_),
    .Q(\mem[3] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _327_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_005_),
    .Q(\mem[3] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _328_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_005_),
    .Q(\mem[3] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _329_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_005_),
    .Q(\mem[3] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _330_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_005_),
    .Q(\mem[3] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _331_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_005_),
    .Q(\mem[3] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _332_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_005_),
    .Q(\mem[3] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _333_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_005_),
    .Q(\mem[3] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _334_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_005_),
    .Q(\mem[3] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _335_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_005_),
    .Q(\mem[3] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _336_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_005_),
    .Q(\mem[3] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _337_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_005_),
    .Q(\mem[3] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _338_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_005_),
    .Q(\mem[3] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _339_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_005_),
    .Q(\mem[3] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _340_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_005_),
    .Q(\mem[3] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _341_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_005_),
    .Q(\mem[3] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _342_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_005_),
    .Q(\mem[3] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _343_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_005_),
    .Q(\mem[3] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _344_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_005_),
    .Q(\mem[3] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _345_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_005_),
    .Q(\mem[3] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _346_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_005_),
    .Q(\mem[3] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _347_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_005_),
    .Q(\mem[3] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _348_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_005_),
    .Q(\mem[3] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _349_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_004_),
    .Q(\mem[2] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _350_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_004_),
    .Q(\mem[2] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _351_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_004_),
    .Q(\mem[2] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _352_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_004_),
    .Q(\mem[2] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _353_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_004_),
    .Q(\mem[2] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _354_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_004_),
    .Q(\mem[2] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _355_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_004_),
    .Q(\mem[2] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _356_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_004_),
    .Q(\mem[2] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _357_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_004_),
    .Q(\mem[2] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _358_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_004_),
    .Q(\mem[2] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _359_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_004_),
    .Q(\mem[2] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _360_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_004_),
    .Q(\mem[2] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _361_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_004_),
    .Q(\mem[2] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _362_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_004_),
    .Q(\mem[2] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _363_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_004_),
    .Q(\mem[2] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _364_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_004_),
    .Q(\mem[2] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _365_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_004_),
    .Q(\mem[2] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _366_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_004_),
    .Q(\mem[2] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _367_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_004_),
    .Q(\mem[2] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _368_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_004_),
    .Q(\mem[2] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _369_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_004_),
    .Q(\mem[2] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _370_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_004_),
    .Q(\mem[2] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _371_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_004_),
    .Q(\mem[2] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _372_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_004_),
    .Q(\mem[2] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _373_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_004_),
    .Q(\mem[2] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _374_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_004_),
    .Q(\mem[2] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _375_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_004_),
    .Q(\mem[2] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _376_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_004_),
    .Q(\mem[2] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _377_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_004_),
    .Q(\mem[2] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _378_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_004_),
    .Q(\mem[2] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _379_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_004_),
    .Q(\mem[2] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _380_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_004_),
    .Q(\mem[2] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _381_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_003_),
    .Q(\mem[1] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _382_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_003_),
    .Q(\mem[1] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _383_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_003_),
    .Q(\mem[1] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _384_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_003_),
    .Q(\mem[1] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _385_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_003_),
    .Q(\mem[1] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _386_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_003_),
    .Q(\mem[1] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _387_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_003_),
    .Q(\mem[1] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _388_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_003_),
    .Q(\mem[1] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _389_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_003_),
    .Q(\mem[1] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _390_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_003_),
    .Q(\mem[1] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _391_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_003_),
    .Q(\mem[1] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _392_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_003_),
    .Q(\mem[1] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _393_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_003_),
    .Q(\mem[1] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _394_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_003_),
    .Q(\mem[1] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _395_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_003_),
    .Q(\mem[1] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _396_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_003_),
    .Q(\mem[1] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _397_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_003_),
    .Q(\mem[1] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _398_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_003_),
    .Q(\mem[1] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _399_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_003_),
    .Q(\mem[1] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _400_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_003_),
    .Q(\mem[1] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _401_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_003_),
    .Q(\mem[1] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _402_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_003_),
    .Q(\mem[1] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _403_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_003_),
    .Q(\mem[1] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _404_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_003_),
    .Q(\mem[1] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _405_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_003_),
    .Q(\mem[1] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _406_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_003_),
    .Q(\mem[1] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _407_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_003_),
    .Q(\mem[1] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _408_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_003_),
    .Q(\mem[1] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _409_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_003_),
    .Q(\mem[1] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _410_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_003_),
    .Q(\mem[1] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _411_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_003_),
    .Q(\mem[1] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _412_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_003_),
    .Q(\mem[1] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _413_ (
    .CLK(wclk),
    .D(data_in[0]),
    .DE(_002_),
    .Q(\mem[0] [0])
  );
  sky130_fd_sc_hd__edfxtp_1 _414_ (
    .CLK(wclk),
    .D(data_in[1]),
    .DE(_002_),
    .Q(\mem[0] [1])
  );
  sky130_fd_sc_hd__edfxtp_1 _415_ (
    .CLK(wclk),
    .D(data_in[2]),
    .DE(_002_),
    .Q(\mem[0] [2])
  );
  sky130_fd_sc_hd__edfxtp_1 _416_ (
    .CLK(wclk),
    .D(data_in[3]),
    .DE(_002_),
    .Q(\mem[0] [3])
  );
  sky130_fd_sc_hd__edfxtp_1 _417_ (
    .CLK(wclk),
    .D(data_in[4]),
    .DE(_002_),
    .Q(\mem[0] [4])
  );
  sky130_fd_sc_hd__edfxtp_1 _418_ (
    .CLK(wclk),
    .D(data_in[5]),
    .DE(_002_),
    .Q(\mem[0] [5])
  );
  sky130_fd_sc_hd__edfxtp_1 _419_ (
    .CLK(wclk),
    .D(data_in[6]),
    .DE(_002_),
    .Q(\mem[0] [6])
  );
  sky130_fd_sc_hd__edfxtp_1 _420_ (
    .CLK(wclk),
    .D(data_in[7]),
    .DE(_002_),
    .Q(\mem[0] [7])
  );
  sky130_fd_sc_hd__edfxtp_1 _421_ (
    .CLK(wclk),
    .D(data_in[8]),
    .DE(_002_),
    .Q(\mem[0] [8])
  );
  sky130_fd_sc_hd__edfxtp_1 _422_ (
    .CLK(wclk),
    .D(data_in[9]),
    .DE(_002_),
    .Q(\mem[0] [9])
  );
  sky130_fd_sc_hd__edfxtp_1 _423_ (
    .CLK(wclk),
    .D(data_in[10]),
    .DE(_002_),
    .Q(\mem[0] [10])
  );
  sky130_fd_sc_hd__edfxtp_1 _424_ (
    .CLK(wclk),
    .D(data_in[11]),
    .DE(_002_),
    .Q(\mem[0] [11])
  );
  sky130_fd_sc_hd__edfxtp_1 _425_ (
    .CLK(wclk),
    .D(data_in[12]),
    .DE(_002_),
    .Q(\mem[0] [12])
  );
  sky130_fd_sc_hd__edfxtp_1 _426_ (
    .CLK(wclk),
    .D(data_in[13]),
    .DE(_002_),
    .Q(\mem[0] [13])
  );
  sky130_fd_sc_hd__edfxtp_1 _427_ (
    .CLK(wclk),
    .D(data_in[14]),
    .DE(_002_),
    .Q(\mem[0] [14])
  );
  sky130_fd_sc_hd__edfxtp_1 _428_ (
    .CLK(wclk),
    .D(data_in[15]),
    .DE(_002_),
    .Q(\mem[0] [15])
  );
  sky130_fd_sc_hd__edfxtp_1 _429_ (
    .CLK(wclk),
    .D(data_in[16]),
    .DE(_002_),
    .Q(\mem[0] [16])
  );
  sky130_fd_sc_hd__edfxtp_1 _430_ (
    .CLK(wclk),
    .D(data_in[17]),
    .DE(_002_),
    .Q(\mem[0] [17])
  );
  sky130_fd_sc_hd__edfxtp_1 _431_ (
    .CLK(wclk),
    .D(data_in[18]),
    .DE(_002_),
    .Q(\mem[0] [18])
  );
  sky130_fd_sc_hd__edfxtp_1 _432_ (
    .CLK(wclk),
    .D(data_in[19]),
    .DE(_002_),
    .Q(\mem[0] [19])
  );
  sky130_fd_sc_hd__edfxtp_1 _433_ (
    .CLK(wclk),
    .D(data_in[20]),
    .DE(_002_),
    .Q(\mem[0] [20])
  );
  sky130_fd_sc_hd__edfxtp_1 _434_ (
    .CLK(wclk),
    .D(data_in[21]),
    .DE(_002_),
    .Q(\mem[0] [21])
  );
  sky130_fd_sc_hd__edfxtp_1 _435_ (
    .CLK(wclk),
    .D(data_in[22]),
    .DE(_002_),
    .Q(\mem[0] [22])
  );
  sky130_fd_sc_hd__edfxtp_1 _436_ (
    .CLK(wclk),
    .D(data_in[23]),
    .DE(_002_),
    .Q(\mem[0] [23])
  );
  sky130_fd_sc_hd__edfxtp_1 _437_ (
    .CLK(wclk),
    .D(data_in[24]),
    .DE(_002_),
    .Q(\mem[0] [24])
  );
  sky130_fd_sc_hd__edfxtp_1 _438_ (
    .CLK(wclk),
    .D(data_in[25]),
    .DE(_002_),
    .Q(\mem[0] [25])
  );
  sky130_fd_sc_hd__edfxtp_1 _439_ (
    .CLK(wclk),
    .D(data_in[26]),
    .DE(_002_),
    .Q(\mem[0] [26])
  );
  sky130_fd_sc_hd__edfxtp_1 _440_ (
    .CLK(wclk),
    .D(data_in[27]),
    .DE(_002_),
    .Q(\mem[0] [27])
  );
  sky130_fd_sc_hd__edfxtp_1 _441_ (
    .CLK(wclk),
    .D(data_in[28]),
    .DE(_002_),
    .Q(\mem[0] [28])
  );
  sky130_fd_sc_hd__edfxtp_1 _442_ (
    .CLK(wclk),
    .D(data_in[29]),
    .DE(_002_),
    .Q(\mem[0] [29])
  );
  sky130_fd_sc_hd__edfxtp_1 _443_ (
    .CLK(wclk),
    .D(data_in[30]),
    .DE(_002_),
    .Q(\mem[0] [30])
  );
  sky130_fd_sc_hd__edfxtp_1 _444_ (
    .CLK(wclk),
    .D(data_in[31]),
    .DE(_002_),
    .Q(\mem[0] [31])
  );
  sky130_fd_sc_hd__edfxtp_1 _445_ (
    .CLK(rclk),
    .D(_000_[0]),
    .DE(_001_),
    .Q(data_out[0])
  );
  sky130_fd_sc_hd__edfxtp_1 _446_ (
    .CLK(rclk),
    .D(_000_[1]),
    .DE(_001_),
    .Q(data_out[1])
  );
  sky130_fd_sc_hd__edfxtp_1 _447_ (
    .CLK(rclk),
    .D(_000_[2]),
    .DE(_001_),
    .Q(data_out[2])
  );
  sky130_fd_sc_hd__edfxtp_1 _448_ (
    .CLK(rclk),
    .D(_000_[3]),
    .DE(_001_),
    .Q(data_out[3])
  );
  sky130_fd_sc_hd__edfxtp_1 _449_ (
    .CLK(rclk),
    .D(_000_[4]),
    .DE(_001_),
    .Q(data_out[4])
  );
  sky130_fd_sc_hd__edfxtp_1 _450_ (
    .CLK(rclk),
    .D(_000_[5]),
    .DE(_001_),
    .Q(data_out[5])
  );
  sky130_fd_sc_hd__edfxtp_1 _451_ (
    .CLK(rclk),
    .D(_000_[6]),
    .DE(_001_),
    .Q(data_out[6])
  );
  sky130_fd_sc_hd__edfxtp_1 _452_ (
    .CLK(rclk),
    .D(_000_[7]),
    .DE(_001_),
    .Q(data_out[7])
  );
  sky130_fd_sc_hd__edfxtp_1 _453_ (
    .CLK(rclk),
    .D(_000_[8]),
    .DE(_001_),
    .Q(data_out[8])
  );
  sky130_fd_sc_hd__edfxtp_1 _454_ (
    .CLK(rclk),
    .D(_000_[9]),
    .DE(_001_),
    .Q(data_out[9])
  );
  sky130_fd_sc_hd__edfxtp_1 _455_ (
    .CLK(rclk),
    .D(_000_[10]),
    .DE(_001_),
    .Q(data_out[10])
  );
  sky130_fd_sc_hd__edfxtp_1 _456_ (
    .CLK(rclk),
    .D(_000_[11]),
    .DE(_001_),
    .Q(data_out[11])
  );
  sky130_fd_sc_hd__edfxtp_1 _457_ (
    .CLK(rclk),
    .D(_000_[12]),
    .DE(_001_),
    .Q(data_out[12])
  );
  sky130_fd_sc_hd__edfxtp_1 _458_ (
    .CLK(rclk),
    .D(_000_[13]),
    .DE(_001_),
    .Q(data_out[13])
  );
  sky130_fd_sc_hd__edfxtp_1 _459_ (
    .CLK(rclk),
    .D(_000_[14]),
    .DE(_001_),
    .Q(data_out[14])
  );
  sky130_fd_sc_hd__edfxtp_1 _460_ (
    .CLK(rclk),
    .D(_000_[15]),
    .DE(_001_),
    .Q(data_out[15])
  );
  sky130_fd_sc_hd__edfxtp_1 _461_ (
    .CLK(rclk),
    .D(_000_[16]),
    .DE(_001_),
    .Q(data_out[16])
  );
  sky130_fd_sc_hd__edfxtp_1 _462_ (
    .CLK(rclk),
    .D(_000_[17]),
    .DE(_001_),
    .Q(data_out[17])
  );
  sky130_fd_sc_hd__edfxtp_1 _463_ (
    .CLK(rclk),
    .D(_000_[18]),
    .DE(_001_),
    .Q(data_out[18])
  );
  sky130_fd_sc_hd__edfxtp_1 _464_ (
    .CLK(rclk),
    .D(_000_[19]),
    .DE(_001_),
    .Q(data_out[19])
  );
  sky130_fd_sc_hd__edfxtp_1 _465_ (
    .CLK(rclk),
    .D(_000_[20]),
    .DE(_001_),
    .Q(data_out[20])
  );
  sky130_fd_sc_hd__edfxtp_1 _466_ (
    .CLK(rclk),
    .D(_000_[21]),
    .DE(_001_),
    .Q(data_out[21])
  );
  sky130_fd_sc_hd__edfxtp_1 _467_ (
    .CLK(rclk),
    .D(_000_[22]),
    .DE(_001_),
    .Q(data_out[22])
  );
  sky130_fd_sc_hd__edfxtp_1 _468_ (
    .CLK(rclk),
    .D(_000_[23]),
    .DE(_001_),
    .Q(data_out[23])
  );
  sky130_fd_sc_hd__edfxtp_1 _469_ (
    .CLK(rclk),
    .D(_000_[24]),
    .DE(_001_),
    .Q(data_out[24])
  );
  sky130_fd_sc_hd__edfxtp_1 _470_ (
    .CLK(rclk),
    .D(_000_[25]),
    .DE(_001_),
    .Q(data_out[25])
  );
  sky130_fd_sc_hd__edfxtp_1 _471_ (
    .CLK(rclk),
    .D(_000_[26]),
    .DE(_001_),
    .Q(data_out[26])
  );
  sky130_fd_sc_hd__edfxtp_1 _472_ (
    .CLK(rclk),
    .D(_000_[27]),
    .DE(_001_),
    .Q(data_out[27])
  );
  sky130_fd_sc_hd__edfxtp_1 _473_ (
    .CLK(rclk),
    .D(_000_[28]),
    .DE(_001_),
    .Q(data_out[28])
  );
  sky130_fd_sc_hd__edfxtp_1 _474_ (
    .CLK(rclk),
    .D(_000_[29]),
    .DE(_001_),
    .Q(data_out[29])
  );
  sky130_fd_sc_hd__edfxtp_1 _475_ (
    .CLK(rclk),
    .D(_000_[30]),
    .DE(_001_),
    .Q(data_out[30])
  );
  sky130_fd_sc_hd__edfxtp_1 _476_ (
    .CLK(rclk),
    .D(_000_[31]),
    .DE(_001_),
    .Q(data_out[31])
  );
endmodule

(* dynports =  1  *)
(* src = "read_ptr_logic.v:7.1-32.10" *)
module read_ptr_logic(rclk, reset, empty, r_en, gray_w_ptr_syn, bin_w_ptr, bin_r_ptr, gray_r_ptr);
  (* src = "read_ptr_logic.v:8.7-8.11" *)
  input rclk;
  wire rclk;
  (* src = "read_ptr_logic.v:9.7-9.12" *)
  input reset;
  wire reset;
  (* src = "read_ptr_logic.v:10.8-10.13" *)
  output empty;
  wire empty;
  (* src = "read_ptr_logic.v:11.7-11.11" *)
  input r_en;
  wire r_en;
  (* src = "read_ptr_logic.v:12.25-12.39" *)
  input [3:0] gray_w_ptr_syn;
  wire [3:0] gray_w_ptr_syn;
  (* src = "read_ptr_logic.v:13.26-13.35" *)
  output [3:0] bin_w_ptr;
  wire [3:0] bin_w_ptr;
  (* src = "read_ptr_logic.v:14.31-14.40" *)
  output [3:0] bin_r_ptr;
  wire [3:0] bin_r_ptr;
  (* src = "read_ptr_logic.v:15.27-15.37" *)
  output [3:0] gray_r_ptr;
  wire [3:0] gray_r_ptr;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(bin_r_ptr[1]),
    .B(bin_w_ptr[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(bin_r_ptr[0]),
    .B(bin_w_ptr[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _17_ (
    .A(bin_r_ptr[2]),
    .B(bin_w_ptr[2]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(bin_r_ptr[3]),
    .B(bin_w_ptr[3]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand4_1 _19_ (
    .A(_04_),
    .B(_05_),
    .C(_06_),
    .D(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(_08_),
    .Y(empty)
  );
  sky130_fd_sc_hd__and3_1 _21_ (
    .A(bin_r_ptr[0]),
    .B(r_en),
    .C(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__and3_1 _22_ (
    .A(bin_r_ptr[1]),
    .B(bin_r_ptr[2]),
    .C(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(bin_r_ptr[1]),
    .A2(_09_),
    .B1(bin_r_ptr[2]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3_1 _24_ (
    .A(reset),
    .B(_10_),
    .C(_11_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _25_ (
    .A1(bin_r_ptr[1]),
    .A2(_09_),
    .B1(reset),
    .Y(_12_)
  );
  sky130_fd_sc_hd__o21a_1 _26_ (
    .A1(bin_r_ptr[1]),
    .A2(_09_),
    .B1(_12_),
    .X(_01_)
  );
  sky130_fd_sc_hd__a21oi_1 _27_ (
    .A1(r_en),
    .A2(_08_),
    .B1(bin_r_ptr[0]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__nor3_1 _28_ (
    .A(reset),
    .B(_09_),
    .C(_13_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__a41oi_1 _29_ (
    .A1(bin_r_ptr[3]),
    .A2(bin_r_ptr[1]),
    .A3(bin_r_ptr[2]),
    .A4(_09_),
    .B1(reset),
    .Y(_14_)
  );
  sky130_fd_sc_hd__o21a_1 _30_ (
    .A1(bin_r_ptr[3]),
    .A2(_10_),
    .B1(_14_),
    .X(_03_)
  );
  (* src = "read_ptr_logic.v:21.5-30.8" *)
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(rclk),
    .D(_02_),
    .Q(bin_r_ptr[0])
  );
  (* src = "read_ptr_logic.v:21.5-30.8" *)
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(rclk),
    .D(_01_),
    .Q(bin_r_ptr[1])
  );
  (* src = "read_ptr_logic.v:21.5-30.8" *)
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(rclk),
    .D(_00_),
    .Q(bin_r_ptr[2])
  );
  (* src = "read_ptr_logic.v:21.5-30.8" *)
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(rclk),
    .D(_03_),
    .Q(bin_r_ptr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "read_ptr_logic.v:18.14-18.62" *)
  bcd_gray btg (
    .bin_addr(bin_r_ptr),
    .gray_addr(gray_r_ptr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "read_ptr_logic.v:19.14-19.66" *)
  gray_bcd gtb (
    .bin_addr(bin_w_ptr),
    .gray_addr(gray_w_ptr_syn)
  );
endmodule

(* dynports =  1  *)
(* src = "synchroniser.v:5.1-14.10" *)
module synchroniser(d, q, clk);
  (* src = "synchroniser.v:6.24-6.25" *)
  input [3:0] d;
  wire [3:0] d;
  (* src = "synchroniser.v:7.30-7.31" *)
  output [3:0] q;
  wire [3:0] q;
  (* src = "synchroniser.v:8.7-8.10" *)
  input clk;
  wire clk;
  (* src = "synchroniser.v:10.27-10.29" *)
  wire [3:0] w1;
  (* module_not_derived = 32'd1 *)
  (* src = "synchroniser.v:11.10-11.39" *)
  d_ff uut_1 (
    .clk(clk),
    .d(d),
    .q(w1)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "synchroniser.v:12.10-12.39" *)
  d_ff uut_2 (
    .clk(clk),
    .d(w1),
    .q(q)
  );
endmodule

(* dynports =  1  *)
(* src = "top_module.v:3.1-21.10" *)
module top_module(rclk, wclk, reset, w_en, r_en, bin_w_ptr, bin_r_ptr, gray_w_ptr, gray_w_ptr_syn, gray_r_ptr, gray_r_ptr_syn, full, empty);
  (* src = "top_module.v:4.7-4.11" *)
  input rclk;
  wire rclk;
  (* src = "top_module.v:5.7-5.11" *)
  input wclk;
  wire wclk;
  (* src = "top_module.v:6.7-6.12" *)
  input reset;
  wire reset;
  (* src = "top_module.v:7.7-7.11" *)
  input w_en;
  wire w_en;
  (* src = "top_module.v:7.12-7.16" *)
  input r_en;
  wire r_en;
  (* src = "top_module.v:8.26-8.35" *)
  output [3:0] bin_w_ptr;
  wire [3:0] bin_w_ptr;
  (* src = "top_module.v:8.36-8.45" *)
  output [3:0] bin_r_ptr;
  wire [3:0] bin_r_ptr;
  (* src = "top_module.v:9.30-9.40" *)
  output [3:0] gray_w_ptr;
  wire [3:0] gray_w_ptr;
  (* src = "top_module.v:9.41-9.55" *)
  output [3:0] gray_w_ptr_syn;
  wire [3:0] gray_w_ptr_syn;
  (* src = "top_module.v:10.30-10.40" *)
  output [3:0] gray_r_ptr;
  wire [3:0] gray_r_ptr;
  (* src = "top_module.v:10.41-10.55" *)
  output [3:0] gray_r_ptr_syn;
  wire [3:0] gray_r_ptr_syn;
  (* src = "top_module.v:11.12-11.16" *)
  output full;
  wire full;
  (* src = "top_module.v:11.17-11.22" *)
  output empty;
  wire empty;
  (* module_not_derived = 32'd1 *)
  (* src = "top_module.v:19.18-19.68" *)
  synchroniser read (
    .clk(wclk),
    .d(gray_r_ptr),
    .q(gray_r_ptr_syn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_module.v:16.20-16.153" *)
  read_ptr_logic rl (
    .bin_r_ptr(bin_r_ptr),
    .empty(empty),
    .gray_r_ptr(gray_r_ptr),
    .gray_w_ptr_syn(gray_w_ptr_syn),
    .r_en(r_en),
    .rclk(rclk),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_module.v:14.21-14.152" *)
  write_ptr_logic wl (
    .bin_w_ptr(bin_w_ptr),
    .full(full),
    .gray_r_ptr_syn(gray_r_ptr_syn),
    .gray_w_ptr(gray_w_ptr),
    .reset(reset),
    .w_en(w_en),
    .wclk(wclk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top_module.v:18.18-18.69" *)
  synchroniser write (
    .clk(rclk),
    .d(gray_w_ptr),
    .q(gray_w_ptr_syn)
  );
endmodule

(* dynports =  1  *)
(* src = "write_ptr_logic.v:8.1-39.10" *)
module write_ptr_logic(wclk, reset, full, w_en, gray_r_ptr_syn, bin_r_ptr, bin_w_ptr, gray_w_ptr);
  (* src = "write_ptr_logic.v:10.7-10.11" *)
  input wclk;
  wire wclk;
  (* src = "write_ptr_logic.v:11.7-11.12" *)
  input reset;
  wire reset;
  (* src = "write_ptr_logic.v:12.8-12.12" *)
  output full;
  wire full;
  (* src = "write_ptr_logic.v:13.7-13.11" *)
  input w_en;
  wire w_en;
  (* src = "write_ptr_logic.v:15.25-15.39" *)
  input [3:0] gray_r_ptr_syn;
  wire [3:0] gray_r_ptr_syn;
  (* src = "write_ptr_logic.v:16.26-16.35" *)
  output [3:0] bin_r_ptr;
  wire [3:0] bin_r_ptr;
  (* src = "write_ptr_logic.v:17.30-17.39" *)
  output [3:0] bin_w_ptr;
  wire [3:0] bin_w_ptr;
  (* src = "write_ptr_logic.v:18.26-18.36" *)
  output [3:0] gray_w_ptr;
  wire [3:0] gray_w_ptr;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  sky130_fd_sc_hd__xnor2_1 _15_ (
    .A(bin_w_ptr[1]),
    .B(bin_r_ptr[1]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__xnor2_1 _16_ (
    .A(bin_w_ptr[0]),
    .B(bin_r_ptr[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__xor2_1 _17_ (
    .A(bin_w_ptr[3]),
    .B(bin_r_ptr[3]),
    .X(_06_)
  );
  sky130_fd_sc_hd__xnor2_1 _18_ (
    .A(bin_w_ptr[2]),
    .B(bin_r_ptr[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand4_1 _19_ (
    .A(_04_),
    .B(_05_),
    .C(_06_),
    .D(_07_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__clkinv_1 _20_ (
    .A(_08_),
    .Y(full)
  );
  sky130_fd_sc_hd__and3_1 _21_ (
    .A(bin_w_ptr[0]),
    .B(w_en),
    .C(_08_),
    .X(_09_)
  );
  sky130_fd_sc_hd__o21bai_1 _22_ (
    .A1(bin_w_ptr[1]),
    .A2(_09_),
    .B1_N(reset),
    .Y(_10_)
  );
  sky130_fd_sc_hd__a21oi_1 _23_ (
    .A1(bin_w_ptr[1]),
    .A2(_09_),
    .B1(_10_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _24_ (
    .A1(w_en),
    .A2(_08_),
    .B1(bin_w_ptr[0]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor3_1 _25_ (
    .A(reset),
    .B(_09_),
    .C(_11_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__and3_1 _26_ (
    .A(bin_w_ptr[2]),
    .B(bin_w_ptr[1]),
    .C(_09_),
    .X(_12_)
  );
  sky130_fd_sc_hd__a41oi_1 _27_ (
    .A1(bin_w_ptr[2]),
    .A2(bin_w_ptr[3]),
    .A3(bin_w_ptr[1]),
    .A4(_09_),
    .B1(reset),
    .Y(_13_)
  );
  sky130_fd_sc_hd__o21a_1 _28_ (
    .A1(bin_w_ptr[3]),
    .A2(_12_),
    .B1(_13_),
    .X(_02_)
  );
  sky130_fd_sc_hd__a21oi_1 _29_ (
    .A1(bin_w_ptr[1]),
    .A2(_09_),
    .B1(bin_w_ptr[2]),
    .Y(_14_)
  );
  sky130_fd_sc_hd__nor3_1 _30_ (
    .A(reset),
    .B(_12_),
    .C(_14_),
    .Y(_03_)
  );
  (* src = "write_ptr_logic.v:26.5-36.8" *)
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(wclk),
    .D(_01_),
    .Q(bin_w_ptr[0])
  );
  (* src = "write_ptr_logic.v:26.5-36.8" *)
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(wclk),
    .D(_00_),
    .Q(bin_w_ptr[1])
  );
  (* src = "write_ptr_logic.v:26.5-36.8" *)
  sky130_fd_sc_hd__dfxtp_1 _33_ (
    .CLK(wclk),
    .D(_03_),
    .Q(bin_w_ptr[2])
  );
  (* src = "write_ptr_logic.v:26.5-36.8" *)
  sky130_fd_sc_hd__dfxtp_1 _34_ (
    .CLK(wclk),
    .D(_02_),
    .Q(bin_w_ptr[3])
  );
  (* module_not_derived = 32'd1 *)
  (* src = "write_ptr_logic.v:21.14-21.62" *)
  bcd_gray btg (
    .bin_addr(bin_w_ptr),
    .gray_addr(gray_w_ptr)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "write_ptr_logic.v:22.14-22.66" *)
  gray_bcd gtb (
    .bin_addr(bin_r_ptr),
    .gray_addr(gray_r_ptr_syn)
  );
endmodule
